### PR TITLE
Patch 1.1

### PR DESCRIPTION
**Pull request by ducktape22**
Fixed some problems 
Added stocks.py and +invest command (WIP)
did some other stuff that I haven't documented on the timeline very well

### CODE REVIEW

**Comment by cactobyte** [comment]
Lyle, Finlay says you are bad at github, do not merge.

**Comment by ducktape22** [comment]
Hello my good friend Boris, I have absolutely no idea how to use Github and
I made a complete mess.
Please help me.
[image: image.png]

**Comment by ducktape22** [comment]
LMAO ME RESPONDING BY EMAIL AND THE IMAGE SAYS IT ALL
cat-meme-cat-funny

**Comment by cactobyte** [comment]
Hello Brother Lyle, this is indeed cooked 💀 

From the screen 📺 to the ring 🥊 to the pen 🖊️ to the king 👑! Where’s my crown 👑 🤷‍♂️ that’s my bling 💍 🤑 always trouble 😈 when I ring

**Comment by OneFishyBoi** [comment]
im gonna merge the things and stuff!!!

**Pull request merged**
